# Generated by Django 3.0.6 on 2020-05-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='qc_file',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='reads',
            field=models.IntegerField(),
        ),
    ]
