# Generated by Django 3.0.8 on 2020-08-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0002_auto_20200801_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='date_submitted',
            new_name='datesubmitted',
        ),
    ]
