# Generated by Django 3.0.6 on 2020-05-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0002_auto_20200513_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='internal_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
