# Generated by Django 3.0.8 on 2020-08-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0004_auto_20200804_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='Name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='location',
            name='Name',
            field=models.CharField(max_length=150),
        ),
    ]
