# Generated by Django 3.0.8 on 2020-08-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0005_auto_20200804_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='gisaid',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='nextstrain',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='pangolin',
        ),
        migrations.AddField(
            model_name='sample',
            name='gisaid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Gisaid_clade', to='cov2cl.GISAIDClade'),
        ),
        migrations.AddField(
            model_name='sample',
            name='nextstrain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Nextstrain_clade', to='cov2cl.NextstrainClade'),
        ),
        migrations.AddField(
            model_name='sample',
            name='pangolin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pangolin_linage', to='cov2cl.PANGOLINLineage'),
        ),
    ]
