# Generated by Django 3.0.6 on 2020-05-17 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0005_auto_20200517_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cou_sampled', to='cov2cl.Country'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='country_exposure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cou_exposure', to='cov2cl.Country'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='div_sampled', to='cov2cl.Division'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='division_exposure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='div_exposure', to='cov2cl.Division'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_sampled', to='cov2cl.Region'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='region_exposure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_exposure', to='cov2cl.Region'),
        ),
    ]
