# Generated by Django 3.0.6 on 2020-05-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0006_auto_20200517_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='qc_file',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='qc_file2',
        ),
        migrations.AddField(
            model_name='genome',
            name='Basecall_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='Basecalled_reads_PHRED_quality',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='Basecalled_reads_length',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='Basecalled_reads_length_vs_reads_PHRED_quality',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='Channel_activity_over_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='General_run_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='Output_over_experiment_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='Read_length_over_experiment_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='Read_quality_over_experiment_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='nanoQC_field',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='genbank_accession',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='gisaid_epi_isl',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
