# Generated by Django 3.0.8 on 2020-08-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0006_auto_20200804_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='Basecall_summary',
            new_name='basecall_summary',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='Basecalled_reads_PHRED_quality',
            new_name='basecalled_reads_PHRED_quality',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='Basecalled_reads_length',
            new_name='basecalled_reads_length',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='Basecalled_reads_length_vs_reads_PHRED_quality',
            new_name='basecalled_reads_length_vs_reads_PHRED_quality',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='Channel_activity_over_time',
            new_name='channel_activity_over_time',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='General_run_summary',
            new_name='general_run_summary',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='Output_over_experiment_time',
            new_name='output_over_experiment_time',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='Read_length_over_experiment_time',
            new_name='read_length_over_experiment_time',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='Read_quality_over_experiment_time',
            new_name='read_quality_over_experiment_time',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='Name',
            new_name='name',
        ),
    ]
