# Generated by Django 3.0.8 on 2020-08-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0007_auto_20200804_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pangolinlineage',
            name='lineage',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
