# Generated by Django 3.0.6 on 2020-07-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0008_snv_cdsseq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
