# Generated by Django 3.0.8 on 2020-08-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0008_auto_20200804_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='pangolinlineage',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
