# Generated by Django 3.0.8 on 2020-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0009_pangolinlineage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='paper_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
