# Generated by Django 3.0.6 on 2020-07-31 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0009_auto_20200729_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='genome',
            name='conclusiones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='reads',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='resultados',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='resumen',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='seq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='cov2cl.GenomeSeq'),
        ),
        migrations.CreateModel(
            name='PangolinLineage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linage', models.CharField(max_length=10)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PangolinFather', to='cov2cl.PangolinLineage')),
            ],
        ),
        migrations.CreateModel(
            name='NextstrainClades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clade', models.CharField(max_length=10)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='NextstrainFather', to='cov2cl.NextstrainClades')),
            ],
        ),
        migrations.CreateModel(
            name='GisaidClades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clade', models.CharField(max_length=10)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='GisaidFather', to='cov2cl.GisaidClades')),
            ],
        ),
        migrations.AddField(
            model_name='genome',
            name='gisaid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Gisaid_clade', to='cov2cl.GisaidClades'),
        ),
        migrations.AddField(
            model_name='genome',
            name='nextstrain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Nextstrain_clade', to='cov2cl.NextstrainClades'),
        ),
        migrations.AddField(
            model_name='genome',
            name='pangolin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pangolin_linage', to='cov2cl.PangolinLineage'),
        ),
    ]
