# Generated by Django 3.0.8 on 2020-08-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0010_sample_paper_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='location_exposure',
        ),
    ]
