# Generated by Django 3.0.6 on 2020-07-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0011_auto_20200731_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=5)),
                ('query', models.CharField(max_length=5)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mutations',
        ),
        migrations.AlterField(
            model_name='gisaidclades',
            name='mutation',
            field=models.ManyToManyField(related_name='variationGisaid', to='cov2cl.Mutation'),
        ),
        migrations.AlterField(
            model_name='nextstrainclades',
            name='mutation',
            field=models.ManyToManyField(related_name='variationNextstrain', to='cov2cl.Mutation'),
        ),
        migrations.AlterField(
            model_name='pangolinlineage',
            name='mutation',
            field=models.ManyToManyField(related_name='variationPangolin', to='cov2cl.Mutation'),
        ),
    ]
