# Generated by Django 3.0.8 on 2020-08-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0012_auto_20200807_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cds',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='cds',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='snv',
            name='cdsseq',
        ),
        migrations.AddField(
            model_name='cds',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cds',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cds',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cds',
            name='pdblink',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='cds',
            name='start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cds',
            name='uniprotlink',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='snv',
            name='annotation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CDSSeq',
        ),
        migrations.DeleteModel(
            name='GenomeSeq',
        ),
    ]
