# Generated by Django 3.0.8 on 2020-08-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0013_auto_20200808_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cds',
            name='annotation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='snv',
            name='cds_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='affected', to='cov2cl.CDS'),
        ),
    ]
