# Generated by Django 3.0.8 on 2020-08-09 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0014_auto_20200808_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
                ('gb_gene_id', models.CharField(max_length=200)),
                ('dbxref_gene_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gene', models.CharField(max_length=100)),
                ('locus_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cds',
            name='gene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding', to='cov2cl.gene'),
        ),
    ]
