# Generated by Django 3.0.8 on 2020-08-09 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0015_auto_20200809_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='mature_protein_region_of_CDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('uniprotlink', models.URLField(null=True)),
                ('pdblink', models.URLField(null=True)),
                ('annotation', models.TextField(null=True)),
                ('cds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generates', to='cov2cl.CDS')),
            ],
        ),
    ]
