# Generated by Django 3.0.8 on 2020-08-09 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0017_auto_20200809_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='snv',
            name='utr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hit', to='cov2cl.utrs'),
        ),
    ]
