# Generated by Django 3.0.8 on 2020-08-09 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0018_snv_utr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='snv',
            name='mature_CDS_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated', to='cov2cl.mature_protein_region_of_CDS'),
        ),
        migrations.AddField(
            model_name='snv',
            name='stem_loop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='affects', to='cov2cl.stem_loop'),
        ),
    ]
