# Generated by Django 3.0.8 on 2020-08-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0019_auto_20200809_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='synonym',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
