# Generated by Django 3.0.8 on 2020-08-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0020_gene_synonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='cds',
            name='exception',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cds',
            name='product',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cds',
            name='protein_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
