# Generated by Django 3.0.8 on 2020-08-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0021_auto_20200809_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='cds',
            name='dbxref',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cds',
            name='gbkey',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cds',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cds',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
