# Generated by Django 3.0.8 on 2020-08-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0022_auto_20200809_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cds',
            name='description',
        ),
    ]
