# Generated by Django 3.0.8 on 2020-08-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0023_remove_cds_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cds',
            name='annotation',
        ),
    ]
