# Generated by Django 3.0.8 on 2020-08-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0024_remove_cds_annotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stem_loop',
            old_name='dbxref_gene_id',
            new_name='dbxref',
        ),
        migrations.RemoveField(
            model_name='stem_loop',
            name='locus_tag',
        ),
        migrations.AddField(
            model_name='stem_loop',
            name='gbkey',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stem_loop',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
