# Generated by Django 3.0.8 on 2020-08-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0025_auto_20200809_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stem_loop',
            name='dbxref',
            field=models.IntegerField(null=True),
        ),
    ]
