# Generated by Django 3.0.8 on 2020-08-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0026_auto_20200809_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stem_loop',
            name='function',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stem_loop',
            name='inference',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
