# Generated by Django 3.0.8 on 2020-08-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0027_auto_20200809_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stem_loop',
            name='dbxref',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
