# Generated by Django 3.0.8 on 2020-08-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0028_auto_20200809_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mature_protein_region_of_cds',
            old_name='annotation',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='mature_protein_region_of_cds',
            old_name='description',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='mature_protein_region_of_cds',
            name='length',
        ),
        migrations.AddField(
            model_name='mature_protein_region_of_cds',
            name='gbkey',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mature_protein_region_of_cds',
            name='protein_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
