# Generated by Django 3.0.8 on 2020-08-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0029_auto_20200809_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mature_protein_region_of_cds',
            name='name',
        ),
    ]
