# Generated by Django 3.0.8 on 2020-08-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0030_remove_mature_protein_region_of_cds_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaidclade',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
