# Generated by Django 3.0.8 on 2020-08-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0031_gisaidclade_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextstrainclade',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
