# Generated by Django 3.0.8 on 2020-09-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0032_nextstrainclade_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snv',
            name='cds_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='affected', to='cov2cl.gene'),
        ),
    ]
