# Generated by Django 3.0.8 on 2020-09-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0033_auto_20200902_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snv',
            old_name='cds_id',
            new_name='gene_id',
        ),
    ]
