# Generated by Django 3.0.8 on 2020-09-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0034_auto_20200902_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='snv',
            name='effect',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
