# Generated by Django 3.0.8 on 2020-09-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0035_snv_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
