# Generated by Django 3.0.6 on 2020-05-13 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cou',
                                              to='cov2cl.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField()),
                ('conclusiones', models.TextField()),
                ('resultados', models.TextField()),
                ('reads', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GenomeSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='div',
                                               to='cov2cl.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='snv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('original', models.CharField(max_length=1)),
                ('change', models.CharField(max_length=1)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gquery',
                                            to='cov2cl.Genome')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greference',
                                                to='cov2cl.Genome')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(max_length=150)),
                ('virus', models.CharField(max_length=150)),
                ('gisaid_epi_isl', models.CharField(max_length=150)),
                ('genbank_accession', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('segment', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('originating_lab', models.CharField(max_length=300)),
                ('submitting_lab', models.CharField(max_length=350)),
                ('authors', models.CharField(max_length=350)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=350)),
                ('date_submitted', models.DateField()),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cou_sampled',
                                   to='cov2cl.Location')),
                ('country_exposure',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cou_exposure',
                                   to='cov2cl.Location')),
                ('division',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='div_sampled',
                                   to='cov2cl.Location')),
                ('division_exposure',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='div_exposure',
                                   to='cov2cl.Location')),
                ('location',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loc_sampled',
                                   to='cov2cl.Location')),
                ('location_exposure',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loc_exposure',
                                   to='cov2cl.Location')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_sampled',
                                             to='cov2cl.Location')),
                ('region_exposure',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_exposure',
                                   to='cov2cl.Location')),
            ],
        ),
        migrations.AddField(
            model_name='genome',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample',
                                    to='cov2cl.Sample'),
        ),
        migrations.AddField(
            model_name='genome',
            name='seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence',
                                    to='cov2cl.GenomeSeq'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg',
                                    to='cov2cl.Region'),
        ),
        migrations.CreateModel(
            name='CDSSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
                ('aac', models.TextField()),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomeseq',
                                             to='cov2cl.GenomeSeq')),
            ],
        ),
        migrations.CreateModel(
            name='CDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='genome',
                                             to='cov2cl.Genome')),
                ('seq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CDSSeq',
                                          to='cov2cl.CDSSeq')),
            ],
        ),
    ]
