# Generated by Django 3.0.6 on 2020-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cov2cl', '0003_sample_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='qc_file2',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='qc_file',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
