# Generated by Django 3.0.6 on 2020-06-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0007_auto_20200518_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='snv',
            name='cdsseq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='snv_seq', to='cov2cl.CDSSeq'),
        ),
    ]
