# Generated by Django 3.0.6 on 2020-07-29 15:03
# Modificado por Dante Travisany 2020-07-29 15:06
from django.db import migrations, models
from django.conf import settings

def create_data(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User(pk=1, username="auth0user", is_active=True , email="dtravisany@dim.uchile.cl")
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cov2cl', '0008_snv_cdsseq'),
    ]

    operations = [
        migrations.RunPython(create_data),
        migrations.AlterField(
            model_name='sample',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
